# Generated by Django 5.0.4 on 2024-04-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('questions_1', models.CharField(max_length=100)),
                ('answer_1', models.CharField(max_length=100)),
                ('answer_2', models.CharField(max_length=100)),
                ('answer_3_right', models.CharField(max_length=100)),
                ('questions_2', models.CharField(max_length=100)),
                ('answer_2_1', models.CharField(max_length=100)),
                ('answer_2_2', models.CharField(max_length=100)),
                ('answer_2_3_right', models.CharField(max_length=100)),
                ('questions_3', models.CharField(max_length=100)),
                ('answer_3_1', models.CharField(max_length=100)),
                ('answer_3_2', models.CharField(max_length=100)),
                ('answer_3_3_right', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Speaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
