# Generated by Django 5.0.4 on 2024-04-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listening',
            name='audio_file',
            field=models.FileField(null=True, upload_to='audio_files/'),
        ),
    ]
