# Generated by Django 5.0.4 on 2024-04-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_listening_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listening',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/'),
        ),
    ]
